---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
    register: update_result
  - name: Print result
    debug:
      var: update_result.stdout_lines
